kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Judy Jenkins Template
    tags: instant-app,Jenkins
  name: jenkins
message: "Login to Jenkins with Openshift credentials"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins
    labels:
      app: jenkins
  spec:
    ports:
    - name: jenkins
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: jenkins
      deploymentconfig: jenkins
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for Jenkins's http service.
    name: jenkins
    labels:
      app: jenkins
  spec:
    to:
      kind: Service
      name: jenkins
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    tags:
    - annotations:
        description: The Jenkins Docker image
        tags: jenkins
      from:
        kind: DockerImage
        name: judyobrien/jenkins:${JENKINS_VERSION}
      importPolicy: {}
      name: ${JENKINS_VERSION}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: jenkins
      deploymentconfig: jenkins
    name: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins
      deploymentconfig: jenkins
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          quay.io/judyobrien/jenkins
        creationTimestamp: null
        labels:
          app: jenkins
          deploymentconfig: jenkins
      spec:
        containers:
        - image: ' '
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 8080
              path: /
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            httpGet:
              port: 8080
              path: /
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: ${JENKINS_MAX_MEMORY}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/jenkins/data
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:${JENKINS_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: jenkins-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${JENKINS_VOLUME_CAPACITY}
parameters:
- displayName: Jenkins version
  value: "latest"
  name: JENKINS_VERSION
  required: true
- description: Volume space available for Jenkins
  displayName: Jenkins Volume Capacity
  name: JENKINS_VOLUME_CAPACITY
  required: true
  value: 1Gi
- displayName: Jenkins Max Memory
  name: JENKINS_MAX_MEMORY
  required: true
  value: 2Gi